name: 新功能/意见/建议
description: 有什么好的建议快提给我吧
labels: [feature]
title: 🚀
body:
  - type: textarea
    id: desc
    attributes:
      label: 简要描述下需要的功能、意见或建议
      value:
    validations:
      required: true
